let rewardSound=true,audioContext;try{rewardSound=localStorage.getItem('kitchen-reward-sound')!=='off'}catch{}
function playSuccess(){
  if(!rewardSound)return;
  const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;
  try{
    audioContext ||= new AudioContext();
    const play=()=>{const now=audioContext.currentTime;[523.25,659.25,783.99].forEach((frequency,index)=>{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();const start=now+index*.14;oscillator.type='sine';oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.055,start+.025);gain.gain.exponentialRampToValueAtTime(.0001,start+.42);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start(start);oscillator.stop(start+.45)})};
    if(audioContext.state==='suspended')audioContext.resume().then(play).catch(()=>{});else play();
  }catch{}
}
const rewardButton=document.getElementById('reward-sound');
function updateRewardButton(){rewardButton.textContent='Success sounds: '+(rewardSound?'on':'off');rewardButton.setAttribute('aria-pressed',String(rewardSound))}
rewardButton.onclick=()=>{rewardSound=!rewardSound;try{localStorage.setItem('kitchen-reward-sound',rewardSound?'on':'off')}catch{}updateRewardButton();if(rewardSound)playSuccess()};updateRewardButton();
const modules=[
{name:'Clean hands',icon:'🧼',art:0,rule:'Wash hands before touching food.',look:'I am about to prepare food.',question:'What do I do first?',choices:['🧼 Wash hands','🥗 Touch the food'],answer:0,why:'Clean hands help keep food safe.',task:'Show your trainer how you wash your hands.',list:['Wet hands.','Use soap.','Rub all parts of your hands.','Rinse.','Dry with a single-use towel.']},
{name:'Ready for work',icon:'👨‍🍳',art:1,rule:'Clean clothes. Hair covered. Clean hands.',look:'I am getting ready for work.',question:'Which choice is ready for work?',choices:['📱 Phone in my hand','👨‍🍳 Clean uniform and covered hair'],answer:1,why:'Wear a clean uniform and cover your hair.',task:'Show your trainer your work uniform.',list:['My uniform is clean.','My hair is covered.','My nails are short and clean.','I follow the workplace jewellery rules.']},
{name:'When I am sick',icon:'🤒',art:3,rule:'I feel sick. I tell my supervisor.',look:'I have vomiting or diarrhoea.',question:'What do I do?',choices:['🗣 Tell my supervisor','🍽 Keep preparing food'],answer:0,why:'Tell your supervisor before handling food.',task:'Practise saying: “I feel sick.”',list:['Stop handling food.','Tell my supervisor.','Follow the instructions I am given.']},
{name:'Separate foods',icon:'🥗',art:2,rule:'Keep raw food away from ready food.',look:'Raw chicken and salad are in the fridge.',question:'Where does sealed raw chicken go?',choices:['⬆ Above the salad','⬇ Below ready-to-eat food'],answer:1,why:'Raw chicken juice must not drip onto ready food.',task:'Show your trainer the raw-food storage area.',list:['Find the ready-to-eat food.','Find the raw food.','Keep raw food covered and separate.']},
{name:'Keep food cold or hot',icon:'❄️',art:2,rule:'Cold food stays cold. Hot food stays hot.',look:'The fridge feels warm.',question:'What do I do?',choices:['🗣 Tell my supervisor','🚪 Leave the fridge door open'],answer:0,why:'A warm fridge needs checking. Tell your supervisor.',task:'Find the fridge temperature display.',list:['Keep the fridge door closed.','Show the temperature display to my trainer.','Ask which limit to follow.']},
{name:'Cook safely',icon:'🌡️',art:1,rule:'Check food with a clean thermometer.',look:'Food looks cooked.',question:'How do I check it?',choices:['👀 Only look at the colour','🌡 Ask my trainer to help check the temperature'],answer:1,why:'Use a thermometer and follow your workplace cooking limits.',task:'Ask your trainer to demonstrate a temperature check.',list:['Find the food thermometer.','Ask how to clean it.','Practise a temperature check with my trainer.']},
{name:'Clean and disinfect',icon:'🧽',art:0,rule:'First clean. Then disinfect.',look:'The worktop is dirty.',question:'What comes first?',choices:['🧽 Clean away the dirt','🧴 Spray over the dirt'],answer:0,why:'Clean first. Then use the approved disinfectant as instructed.',task:'Clean a worktop with your trainer.',list:['Keep food away.','Clean away dirt.','Follow the disinfectant label and trainer instructions.']},
{name:'Problems at work',icon:'🗣',art:3,rule:'Stop. Tell my supervisor.',look:'Glass breaks near food.',question:'What do I do?',choices:['✋ Stop and tell my supervisor','✋ Pick up glass with bare hands'],answer:0,why:'Stop. Keep away. Tell your supervisor.',task:'Show your trainer who you tell about a problem.',list:['Find my supervisor.','Practise reporting a spill.','Practise reporting broken glass.']}
];
const app=document.getElementById('app');let state={done:[],practice:{},attempts:{},last:0};try{state={...state,...JSON.parse(localStorage.getItem('kitchen-progress')||'{}')}}catch{}let sound=false,stage=0,current=0,mode='home';const save=()=>{try{localStorage.setItem('kitchen-progress',JSON.stringify(state))}catch{}};const btn=(text,fn,cls='')=>`<button class="${cls}" data-action="${fn}">${text}</button>`;
function render(html){app.innerHTML=html;window.scrollTo(0,0);app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));if(sound)speak(app.querySelector('h1')?.textContent||'');}function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.rate=.8;speechSynthesis.speak(u)}
function home(){mode='home';render(`<div class="welcome"><div><div class="eyebrow">Your kitchen training</div><h1>Hi Kareem!</h1><p>What are we learning today?</p>${btn('Continue · '+modules[state.last].name,'lesson:'+state.last,'primary')}</div><img class="portrait" src="kareem.jpg" alt="Kareem"></div><div class="grid">${btn('<span>📖</span>Learn<small>One skill at a time</small>','learn','tile')}${btn('<span>🎮</span>Play<small>Practise safe choices</small>','play','tile')}${btn('<span>👨‍🍳</span>Practice at work<small>Try it with your trainer</small>','practice','tile')}${btn('<span>⭐</span>My progress<small>See the skills you have practised</small>','progress','tile')}</div>`)}
function menu(view){mode=view;const title={learn:'Choose a skill',practice:'Try it at work',play:'Choose a game'}[view];render(btn('‹ Home','home','back')+`<h1>${title}</h1>`+(view==='play'?`<div class="grid">${btn('<span>✓ / ✕</span>Safe or unsafe?','safe:0','tile')}${btn('<span>❄️</span>Build the fridge','fridge:0','tile')}${btn('<span>🧼</span>Handwashing order','order:0','tile')}</div>`:`<div class="grid">${modules.map((m,i)=>btn(`<span>${m.icon}</span>${m.name}<small>${state.done.includes(i)?'Lesson practised ✓':'Ready to learn'}</small>`,(view==='practice'?'task:':'lesson:')+i,'tile')).join('')}</div>`))}
function lesson(i,s=0){mode='lesson';current=i;stage=s;gameLocked=false;state.last=i;save();let m=modules[i];const content=[`<h1>${m.look}</h1><div class="scene" style="background-position:${m.art%2?100:0}% ${m.art>1?100:0}%" role="img" aria-label="${['Worker washing hands with soap','Chef in clean work uniform','Raw chicken stored below salad','Worker talking to a supervisor'][m.art]}"></div>${btn('Next','next','primary')}`,`<h1>${m.rule}</h1><p>${m.why}</p>${btn('◖ Hear this','hear')} ${btn('Next','next','primary')}`,`<h1>${m.question}</h1><div class="choices">${m.choices.map((c,j)=>btn(c,'answer:'+j)).join('')}</div><div id="feedback" aria-live="polite"></div>`,`<div class="success">✓</div><h1>Well done, Kareem.</h1><p>${m.task}</p>${btn('Practice with my trainer','task:'+i,'primary')} ${btn('Choose another skill','learn')}`][s];render(btn('‹ Skills','learn','back')+`<div class="lesson"><div class="steps">${['Look','Learn','Choose','Do'].map((x,j)=>`<span class="${j===s?'active':''}">${x}</span>`).join('')}</div>${content}</div>`)}
function answer(j){if(gameLocked)return;let m=modules[current];let a=state.attempts[current]||{total:0,right:0};a.total++;if(j===m.answer)a.right++;state.attempts[current]=a;save();let f=document.getElementById('feedback');if(j===m.answer){gameLocked=true;playSuccess();f.innerHTML=`<div class="feedback">✓ Well done! ${m.why}</div>`+btn('Next','complete','primary');f.querySelector('button').onclick=()=>action('complete')}else{f.innerHTML=`<div class="feedback retry">Let’s try again. ${m.rule}</div>`}if(sound)speak(f.textContent)}
function task(i){current=i;mode='task';let m=modules[i];render(btn('‹ Workplace practice','practice','back')+`<div class="lesson"><div class="eyebrow">With my trainer</div><h1>${m.name}</h1><p>${m.task}</p>${m.list.map(x=>`<label class="check"><input type="checkbox">${x}</label>`).join('')}<p class="muted">Trainer: check each action after watching Kareem do it.</p>${btn('Trainer confirms practice','confirm:'+i,'primary')}<div id="feedback" aria-live="polite"></div></div>`)}
function progress(){mode='progress';render(btn('‹ Home','home','back')+`<h1>My progress</h1><p>${state.done.length} of 8 lessons practised</p><div class="grid">${modules.map((m,i)=>{let a=state.attempts[i],pct=a?Math.round(a.right/a.total*100):0;return `<div class="tile"><h2>${m.icon} ${m.name}</h2><p>${a?`${a.right} correct / ${a.total} choices`:'No choices yet'}</p><progress max="100" value="${pct}" aria-label="${m.name} correct choices"></progress><small>${state.practice[i]?'Workplace practice confirmed ✓':'Workplace practice to do'}</small></div>`}).join('')}</div><div class="notice">Progress is saved on this device. Scores show choices in this app, not certification.<br>Training and practice aid. Follow your trainer’s instructions and workplace procedures. <a href="https://www.dm.gov.ae/municipality-business/food-traders-establishments/" target="_blank" rel="noopener">Dubai Municipality food safety resources</a>.</div>`)}
const scenarios=[['🧼','I wash hands before preparing food.',true,'Clean hands help keep food safe.'],['📱','I touch my phone, then touch salad.',false,'Wash hands after touching your phone.'],['🥗','Raw chicken is above salad.',false,'Store covered raw food below ready-to-eat food.'],['🗣','I feel sick. I tell my supervisor.',true,'Tell your supervisor before handling food.'],['🥄','A spoon falls on the floor. I use it.',false,'Get a clean spoon.']];let gameIndex=0,gameLocked=false,orderIndex=0;
function safe(n){mode='safe';gameIndex=n;gameLocked=false;if(n>=scenarios.length){render(btn('‹ Games','play','back')+`<div class="lesson"><div class="success">⭐</div><h1>Round complete!</h1><p>You practised five kitchen choices.</p>${btn('Play again','safe:0','primary')}</div>`);return}let q=scenarios[n];render(btn('‹ Games','play','back')+`<div class="lesson"><div class="eyebrow">Safe or unsafe · ${n+1} / 5</div><div class="scene" style="background-image:none"><span class="symbol">${q[0]}</span></div><h1>${q[1]}</h1><div class="choices">${btn('✓ Safe','judge:true')}${btn('✕ Unsafe','judge:false')}</div><div id="feedback" aria-live="polite"></div></div>`)}
function fridge(n){mode='fridge';gameIndex=n;gameLocked=false;let food=['🥗 Ready-to-eat salad','🐔 Sealed raw chicken'][n];if(n>1){render(btn('‹ Games','play','back')+`<div class="lesson"><h1>✓ Fridge ready!</h1><p>Covered raw food stays below ready food.</p>${btn('Play again','fridge:0','primary')}</div>`);return}render(btn('‹ Games','play','back')+`<div class="lesson"><div class="eyebrow">Build the fridge</div><h1>Where does it go?</h1><h2>${food}</h2><p>Tap a shelf.</p>${btn('Top shelf · ready-to-eat food','shelf:0','shelf')}${btn('Bottom shelf · raw food','shelf:1','shelf')}<div id="feedback" aria-live="polite"></div></div>`)}
function order(n){mode='order';orderIndex=n;if(n===5){render(btn('‹ Games','play','back')+`<div class="lesson"><h1>✓ Clean hands!</h1><p>Wet. Soap. Rub. Rinse. Dry.</p>${btn('Play again','order:0','primary')}</div>`);return}const steps=['💧 Wet hands','🧴 Use soap','👐 Rub all parts','🚿 Rinse','🧻 Dry with a single-use towel'];render(btn('‹ Games','play','back')+`<div class="lesson"><div class="eyebrow">Handwashing order · ${n+1} / 5</div><h1>${n?'What comes next?':'What comes first?'}</h1><div class="choices">${[3,0,4,1,2].filter(j=>j>=n).map(j=>btn(steps[j],'sequence:'+j)).join('')}</div><div id="feedback" aria-live="polite"></div></div>`)}
function gameFeedback(ok,text,next){let f=document.getElementById('feedback');f.innerHTML=`<div class="feedback ${ok?'':'retry'}">${ok?'✓ Well done.':'Let’s try again.'} ${text}</div>`+(ok?btn('Next',next,'primary'):'');if(ok){playSuccess();gameLocked=true;f.querySelector('button').onclick=()=>action(next)}if(sound)speak(f.textContent)}
function action(a){let [k,v]=a.split(':');let i=Number(v);if(k==='home')home();else if(['learn','practice','play'].includes(k))menu(k);else if(k==='progress')progress();else if(k==='lesson')lesson(i);else if(k==='next')lesson(current,stage+1);else if(k==='answer')answer(i);else if(k==='complete'){if(!state.done.includes(current))state.done.push(current);save();lesson(current,3)}else if(k==='hear')speak(modules[current].rule);else if(k==='task')task(i);else if(k==='confirm'){const inputs=[...app.querySelectorAll('input')];let f=document.getElementById('feedback');if(inputs.every(x=>x.checked)){state.practice[i]=true;save();playSuccess();f.innerHTML='<div class="feedback">✓ Workplace practice confirmed.</div>'}else f.innerHTML='<div class="feedback retry">Complete each action with your trainer first.</div>'}else if(k==='safe')safe(i);else if(k==='judge'&&!gameLocked){let q=scenarios[gameIndex];gameFeedback((v==='true')===q[2],q[3],'safe:'+(gameIndex+1))}else if(k==='fridge')fridge(i);else if(k==='shelf'&&!gameLocked)gameFeedback(i===gameIndex,'Keep covered raw food below ready food.','fridge:'+(gameIndex+1));else if(k==='order')order(i);else if(k==='sequence'){if(i===orderIndex){playSuccess();order(orderIndex+1);}else gameFeedback(false,'Think: wet, soap, rub, rinse, dry.','')}}
document.getElementById('brand').onclick=e=>{e.preventDefault();home()};document.getElementById('sound').onclick=()=>{sound=!sound;document.getElementById('sound').setAttribute('aria-pressed',String(sound));document.getElementById('sound').textContent='◖ Read aloud: '+(sound?'on':'off');if(sound)speak('Read aloud is on');else if('speechSynthesis'in window)speechSynthesis.cancel()};home();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'start_food_safety_lesson',description:'Open a food safety lesson by module number. Does not mark it complete.',inputSchema:{type:'object',properties:{module:{type:'integer',minimum:1,maximum:8}},required:['module'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!Number.isInteger(input.module)||input.module<1||input.module>8)throw Error('Module must be 1 to 8');lesson(input.module-1);return{module:input.module,step:'Look'}}})}catch{}}
