/* Uses the existing buttons, speech, reward sound and progress storage. */
let practiceRound=null,practiceChoiceLock=false;
let showIllustrations=true;try{showIllustrations=localStorage.getItem('kitchen-illustrations')!=='off'}catch{}
function illustrationCheckbox(){return `<label class="illustration-toggle"><input type="checkbox" data-illustrations ${showIllustrations?'checked':''}> Illustrations</label>`}
function questionIllustration(q){const image=QUESTION_ILLUSTRATIONS[q.id];if(!image)return '';if(image.full)return `<img class="question-document-image" data-question-image src="${image.src}" alt="${escapeText(q.question)}" ${showIllustrations?'':'hidden'}>`;return `<div class="question-illustration" data-question-image role="img" aria-label="${escapeText(q.question)}" style="background-image:url('${image.src}');background-position:${image.column*100/3}% ${image.row*100/3}%" ${showIllustrations?'':'hidden'}></div>`}
function bindIllustrationCheckbox(){app.querySelectorAll('[data-illustrations]').forEach(box=>{box.onchange=()=>{showIllustrations=box.checked;try{localStorage.setItem('kitchen-illustrations',showIllustrations?'on':'off')}catch{}app.querySelectorAll('[data-illustrations]').forEach(other=>other.checked=showIllustrations);app.querySelectorAll('[data-question-image]').forEach(image=>image.hidden=!showIllustrations)}})}
const escapeText=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shuffled(items){let result=[...items];for(let n=result.length-1;n>0;n--){const j=Math.floor(Math.random()*(n+1));[result[n],result[j]]=[result[j],result[n]]}return result}
function practiceMenu(){mode='question-practice';render(btn('‹ Games','play','back')+`<h1>Question practice</h1><p>Choose a topic. Practise up to 10 questions.</p>${illustrationCheckbox()}<fieldset class="practice-mode"><legend>Choices</legend><label><input name="practice-level" type="radio" value="simple" checked> Simple · 2 choices</label><label><input name="practice-level" type="radio" value="test"> Test practice · 3–4 choices</label></fieldset><div class="grid">${btn('<span>🎯</span>Mixed practice<small>Questions from every topic</small>','bank-start:all','tile')}${QUESTION_TOPICS.map(t=>btn(`<span>${t.icon}</span>${t.name}<small>${t.rows.length} questions</small>`,'bank-start:'+t.id,'tile')).join('')}</div><div class="notice">${QUESTION_BANK.length} practice questions, including your supplied mock test. These are not an official exam bank.<br>${btn('Questions and sources','bank-review','back')}</div>`)}
function startPractice(topic,level){if(topic!=='all'&&!QUESTION_TOPICS.some(t=>t.id===topic))throw Error('Unknown topic');level=level||app.querySelector('input[name="practice-level"]:checked')?.value||'simple';if(!['simple','test'].includes(level))throw Error('Unknown practice level');let pool=QUESTION_BANK.filter(q=>topic==='all'||q.topic===topic);const stats=state.bankStats||{};pool=shuffled(pool).sort((a,b)=>{const priority=q=>{const s=stats[q.id];return !s?0:s.firstCorrect<s.seen?1:2};return priority(a)-priority(b)});practiceRound={topic,level,questions:pool.slice(0,10).map(q=>({...q,displayChoices:shuffled((level==='simple'?[q.choices[q.answer],shuffled(q.choices.filter((_,i)=>i!==q.answer))[0]]:q.choices).map(text=>({text,correct:text===q.choices[q.answer]})))})),index:0,firstCorrect:0,retried:false};showPracticeQuestion()}
function showPracticeQuestion(){mode='question-practice';practiceChoiceLock=false;const r=practiceRound;if(!r)return practiceMenu();if(r.index>=r.questions.length)return practiceSummary();const q=r.questions[r.index];r.retried=false;render(btn('‹ Choose a topic','bank-menu','back')+`<div class="lesson"><div class="eyebrow">${r.level==='test'?'Test practice':'Simple practice'} · ${r.index+1} / ${r.questions.length}</div>${illustrationCheckbox()}${questionIllustration(q)}<h1>${escapeText(q.question)}</h1>${btn('◖ Hear question','bank-hear','back')}<div class="choices bank-choices">${q.displayChoices.map((choice,i)=>btn(escapeText(choice.text),'bank-answer:'+i)).join('')}</div><div id="feedback" role="status" aria-live="polite"></div></div>`);bindIllustrationCheckbox()}
function answerPractice(index){if(practiceChoiceLock||!practiceRound)return;const r=practiceRound,q=r.questions[r.index],choice=q.displayChoices[index];if(!choice)throw Error('Invalid choice');let feedback=document.getElementById('feedback');if(choice.correct){practiceChoiceLock=true;playSuccess();state.bankStats||={};const stat=state.bankStats[q.id]||{seen:0,firstCorrect:0};stat.seen++;if(!r.retried){stat.firstCorrect++;r.firstCorrect++}state.bankStats[q.id]=stat;save();feedback.innerHTML=`<div class="feedback">✓ Well done! ${escapeText(q.explanation)}</div>`+btn('Next','bank-next','primary');feedback.querySelector('button').onclick=()=>practiceAction('bank-next')}else{r.retried=true;feedback.innerHTML=`<div class="feedback retry">Let’s try again. ${escapeText(q.explanation)}</div>`}if(sound)speak(feedback.textContent)}
function practiceSummary(){const r=practiceRound;render(btn('‹ Choose a topic','bank-menu','back')+`<div class="lesson"><div class="success">⭐</div><h1>Practice complete!</h1><p>You practised ${r.questions.length} questions.</p><p>${r.firstCorrect} correct on the first try.</p>${btn('Practise this topic again','bank-again','primary')} ${btn('Choose a topic','bank-menu')}<p class="muted">This is practice, not an official exam result.</p></div>`)}
function reviewBank(){mode='question-review';render(btn('‹ Practice','bank-menu','back')+`<h1>Questions and sources</h1><p>${QUESTION_BANK.length} practice questions across ${QUESTION_TOPICS.length} topics: 96 original questions and 35 adapted from your mock test.</p>${illustrationCheckbox()}<p class="muted">No publicly accessible official Dubai Municipality exam bank was located. The bank combines original workplace scenarios with your supplied mock test. Overlapping concepts are kept as separately labelled practice variants.</p><p><a target="_blank" rel="noopener" href="${BANK_INFO.source}">${escapeText(BANK_INFO.sourceTitle)}</a><br><span class="muted">Source links checked ${BANK_INFO.checked}. Trainer review recommended.</span></p>${QUESTION_TOPICS.map(t=>`<details class="bank-topic"><summary>${t.icon} ${t.name} · ${t.rows.length}</summary>${QUESTION_BANK.filter(q=>q.topic===t.id).map(q=>`<article class="bank-question"><h2>${q.id} · ${escapeText(q.question)}</h2>${questionIllustration(q)}<ol>${q.choices.map((c,i)=>`<li>${escapeText(c)}${i===q.answer?' ✓ Correct':''}</li>`).join('')}</ol><p>${escapeText(q.explanation)}</p>${q.sourceDocument?`<p class="muted">From ${escapeText(q.sourceDocument)} · question ${q.sourceQuestion}. ${escapeText(q.adaptationNote)}</p>`:''}<a href="${q.sourceUrl}" target="_blank" rel="noopener">${escapeText(q.sourceTitle||'Food Code')} · ${escapeText(q.sourceSection)}</a></article>`).join('')}</details>`).join('')}`)}
function practiceAction(value){const [key,arg]=value.split(':');if(key==='bank-menu')practiceMenu();else if(key==='bank-start')startPractice(arg);else if(key==='bank-answer')answerPractice(Number(arg));else if(key==='bank-next'){if(practiceChoiceLock){practiceRound.index++;showPracticeQuestion()}}else if(key==='bank-again')startPractice(practiceRound.topic,practiceRound.level);else if(key==='bank-review')reviewBank();else if(key==='bank-hear'){const q=practiceRound.questions[practiceRound.index];speak(q.question+'. '+q.displayChoices.map(c=>c.text).join('. '))}}
const originalAction=action;action=function(value){if(value.startsWith('bank-'))practiceAction(value);else originalAction(value)};
const originalMenu=menu;menu=function(view){originalMenu(view);if(view==='play'){const grid=app.querySelector('.grid');const tile=document.createElement('button');tile.className='tile';tile.innerHTML=`<span>🎯</span>Question practice<small>${QUESTION_BANK.length} questions · simple or test practice</small>`;tile.onclick=practiceMenu;grid.appendChild(tile)}};
const originalProgress=progress;progress=function(){originalProgress();const stats=state.bankStats||{};let html='<h2>Question practice by topic</h2><p class="muted">First-try accuracy is separate from lesson progress. Retried answers are counted as practice.</p><div class="grid">';for(const t of QUESTION_TOPICS){const qs=QUESTION_BANK.filter(q=>q.topic===t.id);let seen=0,right=0,unique=0;for(const q of qs){const s=stats[q.id];if(s){seen+=s.seen;right+=s.firstCorrect;unique++}}html+=`<div class="tile"><h2>${t.icon} ${t.name}</h2><p>${unique} / ${qs.length} questions practised</p><small>${seen?right+' / '+seen+' correct on first try':'Ready to practise'}</small><progress max="100" value="${seen?Math.round(right/seen*100):0}" aria-label="${t.name} first-try accuracy"></progress></div>`}html+='</div>';const section=document.createElement('section');section.className='bank-progress';section.innerHTML=html;app.appendChild(section)};

const originalIllustrationRender=render;render=function(html){originalIllustrationRender(html);bindIllustrationCheckbox()};